spring:
  datasource:
    platform: postgres
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 300000
      leak-detection-threshold: 10000
    username: dev
    password: dev
    url: jdbc:postgresql://localhost:5432/ipohondrie
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/changelog-master.xml
    url: jdbc:postgresql://localhost:5432/ipohondrie
    user: dev
    password: dev
    enabled: true
