spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 300000
      leak-detection-threshold: 10000
    username: dev
    password: dev
    url: jdbc:postgresql://localhost:5432/ipohondrie
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
